"""Rename metrics to segformer metrics

Revision ID: 042de00eee1b
Revises: e3844dc4110e
Create Date: 2026-08-09 17:44:25.544929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042de00eee1b'
down_revision: Union[str, Sequence[str], None] = 'e3844dc4110e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('a_acc', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('m_iou', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('m_acc', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('m_dice', sa.Float(), nullable=True))
    op.drop_column('model_versions', 'accuracy')
    op.drop_column('model_versions', 'precision')
    op.drop_column('model_versions', 'recall')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('model_versions', sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('model_versions', sa.Column('accuracy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('model_versions', 'm_dice')
    op.drop_column('model_versions', 'm_acc')
    op.drop_column('model_versions', 'm_iou')
    op.drop_column('model_versions', 'a_acc')
    # ### end Alembic commands ###
