"""Update scam_reports table

Revision ID: 45368bf51fde
Revises: c5d636f20434
Create Date: 2026-08-06 19:45:08.823959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45368bf51fde'
down_revision: Union[str, Sequence[str], None] = 'c5d636f20434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scam_reports', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('scam_reports', sa.Column('platform', sa.String(length=50), nullable=True))
    op.add_column('scam_reports', sa.Column('reference_url', sa.String(length=512), nullable=True))
    op.add_column('scam_reports', sa.Column('allow_research_use', sa.Boolean(), nullable=False))
    op.add_column('scam_reports', sa.Column('admin_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scam_reports', 'admin_note')
    op.drop_column('scam_reports', 'allow_research_use')
    op.drop_column('scam_reports', 'reference_url')
    op.drop_column('scam_reports', 'platform')
    op.drop_column('scam_reports', 'category')
    # ### end Alembic commands ###
