"""phase_2_indexes

Revision ID: 8b428eff3721
Revises: c42a6b7c284c
Create Date: 2026-08-09 16:02:00.890000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b428eff3721'
down_revision: Union[str, Sequence[str], None] = 'c42a6b7c284c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_admin_id'), 'audit_log', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_scam_reports_category'), 'scam_reports', ['category'], unique=False)
    op.create_index(op.f('ix_scam_reports_created_at'), 'scam_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_scam_reports_status'), 'scam_reports', ['status'], unique=False)
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_index(op.f('ix_scans_user_id'), 'scans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_user_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_index(op.f('ix_scam_reports_status'), table_name='scam_reports')
    op.drop_index(op.f('ix_scam_reports_created_at'), table_name='scam_reports')
    op.drop_index(op.f('ix_scam_reports_category'), table_name='scam_reports')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_admin_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    # ### end Alembic commands ###
