"""Phase 2 Structured Audit and Report Version

Revision ID: c42a6b7c284c
Revises: a1b2c3d4e5f6
Create Date: 2026-08-09 15:41:26.628687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c42a6b7c284c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('entity_type', sa.String(length=50), nullable=True))
    op.add_column('audit_log', sa.Column('entity_id', sa.String(length=255), nullable=True))
    op.add_column('audit_log', sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_log', sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_log', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('audit_log', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_log', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('audit_log', sa.Column('request_id', sa.String(length=100), nullable=True))
    op.add_column('scam_reports', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scam_reports', 'version')
    op.drop_column('audit_log', 'request_id')
    op.drop_column('audit_log', 'user_agent')
    op.drop_column('audit_log', 'ip_address')
    op.drop_column('audit_log', 'reason')
    op.drop_column('audit_log', 'after_state')
    op.drop_column('audit_log', 'before_state')
    op.drop_column('audit_log', 'entity_id')
    op.drop_column('audit_log', 'entity_type')
    # ### end Alembic commands ###
