"""Add Phase 4 ModelVersion fields

Revision ID: cd0116a8d7bc
Revises: 8b428eff3721
Create Date: 2026-08-09 16:18:44.755602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd0116a8d7bc'
down_revision: Union[str, Sequence[str], None] = '8b428eff3721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('artifact_checksum', sa.String(length=256), nullable=True))
    op.add_column('model_versions', sa.Column('framework_compatibility', sa.String(length=50), nullable=True))
    op.add_column('model_versions', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('precision', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('recall', sa.Float(), nullable=True))
    op.add_column('model_versions', sa.Column('dataset_reference', sa.String(length=256), nullable=True))
    op.add_column('model_versions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('model_versions', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('model_versions', sa.Column('deployment_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'model_versions', 'admins', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.drop_column('model_versions', 'deployment_history')
    op.drop_column('model_versions', 'status')
    op.drop_column('model_versions', 'created_by')
    op.drop_column('model_versions', 'dataset_reference')
    op.drop_column('model_versions', 'recall')
    op.drop_column('model_versions', 'precision')
    op.drop_column('model_versions', 'accuracy')
    op.drop_column('model_versions', 'framework_compatibility')
    op.drop_column('model_versions', 'artifact_checksum')
    # ### end Alembic commands ###
