"""add xai_explanation to scans

Revision ID: efdfc08f2155
Revises: 9a0123c45678
Create Date: 2026-09-03 03:48:51.566910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efdfc08f2155'
down_revision: Union[str, Sequence[str], None] = '9a0123c45678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('xai_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'xai_explanation')
    # ### end Alembic commands ###
